# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"&\n\x10\x43\x61lculateRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"M\n\x11\x43\x61lculateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x11\n\thas_error\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2@\n\nCalculator\x12\x32\n\tCalculate\x12\x11.CalculateRequest\x1a\x12.CalculateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATEREQUEST']._serialized_start=20
  _globals['_CALCULATEREQUEST']._serialized_end=58
  _globals['_CALCULATERESPONSE']._serialized_start=60
  _globals['_CALCULATERESPONSE']._serialized_end=137
  _globals['_CALCULATOR']._serialized_start=139
  _globals['_CALCULATOR']._serialized_end=203
# @@protoc_insertion_point(module_scope)
